* 5.1.0

- Add ability to pass custom headers for Invidious requests.
- "q" now forcefully closes the video view for a more consistent experience.
- Add chapter info to =empv-media-title=, making it easier to identify your position in media.
- Add =empv-player-state= variable and hooks:
  - =empv-media-title-changed-hook= for title changes.
  - =empv-player-state-changed-hook= for player state changes.
- Run =empv-player-state-change-hook= at the correct time to improve reliability.
- =empv-youtube-tabulated-video-headers=: accessor now accepts a function for greater flexibility.
- Add =Contents= section and update =Getting notified on media change= in docs.
- Mark some buffers as hidden for a cleaner buffer list.
- Fix MELPA badge link and add stable MELPA badge.
- Add note about the CHANGELOG to the README.

* 5.0.0

- Added a new public variable =empv-current-media-title=. You can use this for various stuff, like putting the song name in the ~global-mode-line~ etc.
- Improved the toggling of video display. When video is enabled, the mpv window now appears immediately (even before buffering completes), this should improve the experience with video toggling.
- Improved event displaying on certain situations, like video visibility changes and pause status changes. Now you should see events for them in the echo area.
- Added a dedicated hydra for empv commands, with notes in the README for usage. Thanks @oreodave!
- Fixed customization types for improved compatibility with Emacs customization. Thanks @Ban3.
- Added =empv-playlist-load-from-file=, allowing playlist selection and playback from =empv-playlist-dir=. This is now bound to "L" in =empv-map=.
- Enabled playback of remote files via SFTP for SSH/SSHX Tramp URIs, ensuring seamless operation both locally and remotely. Thanks @oreodave!
- Added the ability to bookmark all types of URLs, including radio streams and Subsonic resources. (See ~empv-bookmark-set~ and ~empv-bookmark-jump~ functions.)
- Now displays bookmarked radio channels under a separate "Favorites" group.
- Warns user to configure =empv-invidious-instance= when missing (improves troubleshooting).
- Improved color readability in the =empv-display-current= function.

* 4.10.1

- Improved Embark actions for Subsonic results
- Adopt new consult-async API, see #92
- Add bookmarks integration for YouTube search results
- Various codebase improvements.

* 4.9.0

- Subsonic support!
  - Here are the functions that you can use:
    - empv-subsonic-search
    - empv-subsonic-songs
    - empv-subsonic-albums
    - empv-subsonic-artists
  - and here are the customization options:
    - empv-subsonic-url
    - empv-subsonic-username
    - empv-subsonic-password
- Various codebase improvements.

* 4.6.0

- YouTube channels support
  - Now you can hit ~C~ (or call ~empv-youtube-results-open-current-channel~) on a video result and it will show you videos of corresponding channel (it will ask if you want to sort by newest or most popular before listing the videos).
  - You can also search for channels using ~empv-youtube-channel~. Selecting a channel will trigger the workflow I mentioned above.
- Various quality of life improvements.
- ~empv-play-media-at-point~ supports more things. Try it on things that looks like a media file/stream!

* 4.5.0

- Add ~empv-ytdl-download-options~

* 4.4.0

- Now tabulated YouTube searches will have their own buffer, instead of reusing a single buffer
- Add ability to load more results in YouTube results mode. You can hit ~m~ and there will be more results.
- Add ~empv-youtube-tabulated-new-entries-hook~, which is called after loading candidates to the buffer
- Make ~youtube-tabulated-mode~ headers fully customizable. See variables ~empv-youtube-tabulated-video-headers~, ~empv-youtube-tabulated-playlist-headers~.
- Overall YouTube enchantments
- Various fixes

* 4.1.0

- Add ~empv-youtube-download~.
- Add ~empv-event~ to observe mpv generated events.
- Make ~empv-start~ take multiple URIs.
- Add ~empv-fd-binary~ to provide flexibility with the fd executable.
- Now you can edit ~empv-display-current-format~ to change how ~empv-display-current~ displays information.
- Ask user if they want to search for the web if lyrics is not found
- Add ~empv-youtube-become-tabulated~ embark action. Now you can convert your ~completing-read~ query to a tabulated one mid-query with this action.
- Make ~empv-play-or-enqueue~ default binding for playing media. Now empv asks you to play given media directly or enqueue it.
- Some bug fixes.

* 4.0.0

- Various fixes.
- Moved ~embark~ to ~empv.el~ again.
- Added two new interactive functions for lyrics management:
  - ~empv-lyrics-current~
  - ~empv-lyrics-show~
- Added new utility functions:
  - ~empv-toggle-current-loop~
  - ~empv-toggle-playlist-loop~
  - ~empv-play-media-at-point~
- Media chapters are now supported. You can use following functions:
  - ~empv-chapter-next~
  - ~empv-chapter-prev~
  - ~empv-chapter-select~
- Now currently played radio is marked with ~[CURRENT]~ in ~empv-play-radio~.
- ~empv-display-current~ is improved.
  - It shows if current file or playlist is on loop.
  - It shows the current volume level and play speed if they differ from the default value.
  - It shows the chapter related information, if available.
- Volume now can be increased to ~volume-max~ value of mpv.
- Now thumbnail downloading on ~empv-youtube-tabulated~ can be disabled by setting ~empv-youtube-thumbnail-quality~ to nil
- Now ~empv-video-dir~ and ~empv-audio-dir~ can be list of directories instead of a single directory.

* 3.0.0

- Moved ~embark~ support into another file, ~empv-embark.el~. Now you need to ~require~ this file to be able to call ~empv-initialize-embark~.
- Removed ~versuri~. I'll add a different, more accurate method for getting lyrics for given song.
- Added capture functionality to ~empv-log-current-radio-song-name~. Now you can add arbitrary text along with the song name while you are capturing it, just call ~empv-log-current-radio-song-name~ with prefix argument. (Simply do ~C-u~ before calling it)
- Fixes:
  - Fixed some bindings.
  - Did a code clean-up, cleared all byte compile warnings.
  - Fixed a memory leak.

* 2.0.0

- ~consult-empv.el~ is removed. Now ~empv.el~ integrates itself with ~consult~ automatically, if it's found on your system. Use default functions instead of ~consult-empv-*~ functions. (e.g. Use ~empv-youtube~ instead of ~consult-empv-youtube~).
- Better ~embark~ support. (Add ~(empv-initialize-embark)~ to your init file to enable it.)
  - Now you can do ~embark-act~ on a file or folder anywhere in Emacs and you'll get the following actions:
    - ~empv-play~
    - ~empv-enqueue~
  - Playlist items have the following extra actions:
    - ~empv-playlist-move~ → Move playlist item to selected place (~top~, ~bottom~, ~next~, ~index~).
    - ~empv-playlist-remove~ → Remove item from the playlist.
    - ~empv-playlist-remove-others~ → Remove all items from the playlist except the selected item.
  - YouTube results have the following extra actions:
    - ~empv-play~
    - ~empv-enqueue~
    - ~empv-youtube-copy-link~
    - ~empv-youtube-show-comments~
- New functions:
  - ~empv-enqueue-next~ → Add item to playlist as next item to play.
  - ~empv-copy-path~
- ~read-multiple-choice~ is the default action selector, instead of ~completing-read~. See the ~empv-action-handler~ variable, if you want to use old behavior.
- YouTube tabulated mode changes:
  - It uses =P= instead of =p= to start playing current result. =p= is bound to ~previous-line~ and =n= is bound to next line. Also =j= and =k= are bound to ~next-line~ and ~previous-line~ respectively.
  - New binding: =c=. Shows comments of current result in a nicely formatted org buffer.

- Misc:
  - More echo area messages to inform user about what's going on.
  - Better playlist management.
    - Instead of showing path/uri, show media title whenever it's possible. (This is generally only possible after the media is played, not before.)

* 0.1

- Initial release
