* 3.0.0

- Moved ~embark~ support into another file, ~empv-embark.el~. Now you need to ~require~ this file to be able to call ~empv-initialize-embark~.
- Removed ~versuri~. I'll add a different, more accurate method for getting lyrics for given song.
- Added capture functionality to ~empv-log-current-radio-song-name~. Now you can add arbitrary text along with the song name while you are capturing it, just call ~empv-log-current-radio-song-name~ with prefix argument. (Simply do ~C-u~ before calling it)
- Fixes:
  - Fixed some bindings.
  - Did a code clean-up, cleared all byte compile warnings.
  - Fixed a memory leak.

* 2.0.0

- ~consult-empv.el~ is removed. Now ~empv.el~ integrates itself with ~consult~ automatically, if it's found on your system. Use default functions instead of ~consult-empv-*~ functions. (e.g. Use ~empv-youtube~ instead of ~consult-empv-youtube~).
- Better ~embark~ support. (Add ~(empv-initialize-embark)~ to your init file to enable it.)
  - Now you can do ~embark-act~ on a file or folder anywhere in Emacs and you'll get the following actions:
    - ~empv-play~
    - ~empv-enqueue~
  - Playlist items have the following extra actions:
    - ~empv-playlist-move~ → Move playlist item to selected place (~top~, ~bottom~, ~next~, ~index~).
    - ~empv-playlist-remove~ → Remove item from the playlist.
    - ~empv-playlist-remove-others~ → Remove all items from the playlist except the selected item.
  - YouTube results have the following extra actions:
    - ~empv-play~
    - ~empv-enqueue~
    - ~empv-youtube-copy-link~
    - ~empv-youtube-show-comments~
- New functions:
  - ~empv-enqueue-next~ → Add item to playlist as next item to play.
  - ~empv-copy-path~
- ~read-multiple-choice~ is the default action selector, instead of ~completing-read~. See the ~empv-action-handler~ variable, if you want to use old behavior.
- YouTube tabulated mode changes:
  - It uses =P= instead of =p= to start playing current result. =p= is bound to ~previous-line~ and =n= is bound to next line. Also =j= and =k= are bound to ~next-line~ and ~previous-line~ respectively.
  - New binding: =c=. Shows comments of current result in a nicely formatted org buffer.

- Misc:
  - More echo area messages to inform user about what's going on.
  - Better playlist management.
    - Instead of showing path/uri, show media title whenever it's possible. (This is generally only possible after the media is played, not before.)

* 0.1

- Initial release
